version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      root-dev-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      website-dev-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
